package log

import (
	"fmt"
	"runtime"
	"strings"
)

func addCaller(fields Fields) Fields {
	if fields == nil {
		fields = Fields{}
	}

	if _, ok := fields["caller"]; !ok {
		fields["caller"] = getCaller()
	}

	return fields
}

func getCaller() string {
	for i := 3; ; i++ {
		_, file, line, _ := runtime.Caller(i)
		if file == "<autogenerated>" {
			continue
		}

		return fmt.Sprintf("%s:%d", trimPath(file), line)
	}
}

func trimPath(path string) string {
	//
	// For details, see http://goo.gl/FL2U8s.

	if idx := strings.LastIndexByte(path, '/'); idx >= 0 {
		if idx := strings.LastIndexByte(path[:idx], '/'); idx >= 0 {
			// Keep everything after the penultimate separator.
			return path[idx+1:]
		}
	}

	return path
}
