// Code generated by protoc-gen-go. DO NOT EDIT.
// source: howdy.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HowdyResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HowdyResponse) Reset()         { *m = HowdyResponse{} }
func (m *HowdyResponse) String() string { return proto.CompactTextString(m) }
func (*HowdyResponse) ProtoMessage()    {}
func (*HowdyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_howdy_847e700a6c092160, []int{0}
}
func (m *HowdyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HowdyResponse.Unmarshal(m, b)
}
func (m *HowdyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HowdyResponse.Marshal(b, m, deterministic)
}
func (dst *HowdyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HowdyResponse.Merge(dst, src)
}
func (m *HowdyResponse) XXX_Size() int {
	return xxx_messageInfo_HowdyResponse.Size(m)
}
func (m *HowdyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HowdyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HowdyResponse proto.InternalMessageInfo

func (m *HowdyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HowdyResponse)(nil), "main.HowdyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HowdyServiceClient is the client API for HowdyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HowdyServiceClient interface {
	Howdy(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HowdyResponse, error)
}

type howdyServiceClient struct {
	cc *grpc.ClientConn
}

func NewHowdyServiceClient(cc *grpc.ClientConn) HowdyServiceClient {
	return &howdyServiceClient{cc}
}

func (c *howdyServiceClient) Howdy(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HowdyResponse, error) {
	out := new(HowdyResponse)
	err := c.cc.Invoke(ctx, "/main.HowdyService/Howdy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HowdyServiceServer is the server API for HowdyService service.
type HowdyServiceServer interface {
	Howdy(context.Context, *empty.Empty) (*HowdyResponse, error)
}

func RegisterHowdyServiceServer(s *grpc.Server, srv HowdyServiceServer) {
	s.RegisterService(&_HowdyService_serviceDesc, srv)
}

func _HowdyService_Howdy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HowdyServiceServer).Howdy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.HowdyService/Howdy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HowdyServiceServer).Howdy(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _HowdyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.HowdyService",
	HandlerType: (*HowdyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Howdy",
			Handler:    _HowdyService_Howdy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "howdy.proto",
}

func init() { proto.RegisterFile("howdy.proto", fileDescriptor_howdy_847e700a6c092160) }

var fileDescriptor_howdy_847e700a6c092160 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc8, 0x2f, 0x4f,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x92, 0x4e,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94,
	0x40, 0x95, 0x28, 0x69, 0x72, 0xf1, 0x7a, 0x80, 0x74, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x46, 0x6e, 0x5c, 0x3c, 0x60, 0xa5, 0xc1, 0xa9, 0x45, 0x65, 0x99,
	0xc9, 0xa9, 0x42, 0x66, 0x5c, 0xac, 0x60, 0xbe, 0x90, 0x98, 0x1e, 0xc4, 0x06, 0x3d, 0x98, 0x0d,
	0x7a, 0xae, 0x20, 0x1b, 0xa4, 0x84, 0xf5, 0x40, 0xf6, 0xeb, 0xa1, 0x98, 0xaf, 0xc4, 0x90, 0xc4,
	0x06, 0x56, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x02, 0x85, 0xe0, 0xdf, 0xab, 0x00, 0x00,
	0x00,
}
